name: fold-vitest
services:
  fold:
    build: .
    container_name: fold
    environment:
      - INPUT_DIR=/service/init
      - INPUT_WORK_DIR=/service/fe
      - INPUT_TEST=npm install && npm run test
    ports:
      - '3333:3333'
    volumes:
      - /Users/ognerezov/pro/fold-data:/service:rw
