package openapi

import (
	"errors"
	"fmt"
	"fold/db"
	"strings"
)

var (
	Authorization = "Authorization"
)

type ApiDescription struct {
	Openapi    string          `json:"openapi,omitempty"`
	Info       Info            `json:"info,omitempty"`
	Servers    []Server        `json:"servers,omitempty"`
	Paths      map[string]Path `json:"paths,omitempty"`
	Components Components      `json:"components,omitempty"`
}

func InitApi(path string, port int, version string) *ApiDescription {
	return &ApiDescription{
		Openapi: "3.0.1",
		Info: Info{
			Title:       "Api for path " + path,
			Version:     version,
			Description: "Generated by fold server for path " + path,
		},
		Paths:      map[string]Path{},
		Components: Components{},
		Servers: []Server{
			{Url: fmt.Sprintf("http://localhost:%v", port)},
		},
	}
}

func (a *ApiDescription) DescribeRawGet(route string, summary string, m string) {
	a.Describe(route, Path{
		"get": Method{
			Summary: summary,
			Responses: map[string]Response{
				"200": {
					Description: "Raw file",
					Content: map[string]Content{
						m: {
							Schema: Schema{
								Type:   "string",
								Format: m,
							},
						},
					},
				},
			},
		},
	})
}

func (a *ApiDescription) Save(path string) error {
	return db.SaveJson(path, *a)
}

type Info struct {
	Title       string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
}

type Server struct {
	Url         string         `json:"url,omitempty"`
	Description string         `json:"description,omitempty"`
	Variables   map[string]any `json:"variables,omitempty"`
}

type Example struct {
	Summary       string         `json:"summary,omitempty"`
	Value         map[string]any `json:"value,omitempty"`
	ExternalValue string         `json:"externalValue,omitempty"`
	Ref           string         `json:"$ref,omitempty"`
}

type Parameter struct {
	Name     string             `json:"name,omitempty"`
	In       string             `json:"in,omitempty"`
	Required bool               `json:"required,omitempty"`
	Style    string             `json:"style,omitempty"`
	Schema   Schema             `json:"schema,omitempty"`
	Examples map[string]Example `json:"examples,omitempty"`
}

type Schema struct {
	Type                 string            `json:"type,omitempty"`
	Properties           map[string]Schema `json:"properties,omitempty"`
	Description          string            `json:"description,omitempty"`
	Format               string            `json:"format,omitempty"`
	OneOf                []Schema          `json:"oneOf,omitempty"`
	Ref                  string            `json:"$ref,omitempty"`
	Required             []string          `json:"required,omitempty"`
	AdditionalProperties bool              `json:"additionalProperties,omitempty"`
	Encoding             map[string]any    `json:"encoding,omitempty"`
}

type RequestBody struct {
	Ref         string             `json:"$ref,omitempty"`
	Description string             `json:"description,omitempty"`
	Content     map[string]Content `json:"content,omitempty"`
	Required    bool               `json:"required,omitempty"`
}

type Content struct {
	Schema      Schema             `json:"schema,omitempty"`
	Examples    map[string]Example `json:"examples,omitempty"`
	Description string             `json:"description,omitempty"`
}

type Response struct {
	Description string             `json:"description,omitempty"`
	Content     map[string]Content `json:"content,omitempty"`
}

type Path map[string]any

type Method struct {
	Summary     string              `json:"summary,omitempty"`
	Parameters  []Parameter         `json:"parameters,omitempty"`
	RequestBody *RequestBody        `json:"requestBody,omitempty"`
	Responses   map[string]Response `json:"responses,omitempty"`
	Security    map[string][]string `json:"security,omitempty"`
}

func (m *Method) WithParams(params []Parameter) *Method {
	if len(params) > 0 {
		m.Parameters = params
	}
	return m
}

type Components struct {
	RequestBodies   map[string]RequestBody    `json:"requestBodies,omitempty"`
	Schemas         map[string]Schema         `json:"schemas,omitempty"`
	Examples        map[string]Example        `json:"examples,omitempty"`
	Parameters      map[string]Parameter      `json:"parameters,omitempty"`
	SecuritySchemes map[string]SecuritySchema `json:"securitySchemes,omitempty"`
}

type SecuritySchema struct {
	Type         string `json:"type,omitempty"`
	Name         string `json:"name,omitempty"`
	Scheme       string `json:"scheme,omitempty"`
	BearerFormat string `json:"bearerFormat,omitempty"`
	In           string `json:"in,omitempty"`
	Secret       string
}

func (s *SecuritySchema) SecurityHeader() (*string, *string) {
	if s.In == "" || strings.ToLower(s.In) == "header" || strings.ToLower(s.In) == "headers" {
		if s.Type == "http" || s.Type == "https" {
			val := fmt.Sprintf("%s %s", s.Scheme, s.Secret)
			return &Authorization, &val
		}
		if strings.ToLower(s.Type) == "apikey" {
			return &s.Name, &s.Secret
		}

		panic(errors.New("invalid security header type: " + s.Type))
	}
	return nil, nil
}

func (s *SecuritySchema) SecurityQuery() *string {
	if strings.ToLower(s.In) == "query" {
		if strings.ToLower(s.Type) == "apikey" {
			val := fmt.Sprintf("%s=%s", s.Name, s.Secret)
			return &val
		}
		panic(errors.New("invalid security query type: " + s.Type))
	}
	return nil
}
