package openapi

import (
	"fmt"
	"fold/db"
)

type ApiDescription struct {
	Openapi    string          `json:"openapi,omitempty"`
	Info       Info            `json:"info,omitempty"`
	Servers    []Server        `json:"servers,omitempty"`
	Paths      map[string]Path `json:"paths,omitempty"`
	Components Components      `json:"components,omitempty"`
}

func InitApi(path string, port int, version string) *ApiDescription {
	return &ApiDescription{
		Openapi: "3.0.1",
		Info: Info{
			Title:       "Api for path " + path,
			Version:     version,
			Description: "Generated by fold server for path " + path,
		},
		Paths:      map[string]Path{},
		Components: Components{},
		Servers: []Server{
			{Url: fmt.Sprintf("http://localhost:%v", port)},
		},
	}
}

func (a *ApiDescription) DescribeRawGet(route string, summary string, m string) {
	a.Describe(route, Path{
		"get": Method{
			Summary: summary,
			Responses: map[string]Response{
				"200": {
					Description: "Raw file",
					Content: map[string]Content{
						m: {
							Schema: Schema{
								Type:   "string",
								Format: m,
							},
						},
					},
				},
			},
		},
	})
}

func (a *ApiDescription) Save(path string) error {
	return db.Save(path, *a)
}

type Info struct {
	Title       string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
}

type Server struct {
	Url         string         `json:"url,omitempty"`
	Description string         `json:"description,omitempty"`
	Variables   map[string]any `json:"variables,omitempty"`
}

type Example struct {
	Summary       string         `json:"summary,omitempty"`
	Value         map[string]any `json:"value,omitempty"`
	ExternalValue string         `json:"externalValue,omitempty"`
	Ref           string         `json:"$ref,omitempty"`
}

type Parameter struct {
	Name     string             `json:"name,omitempty"`
	In       string             `json:"in,omitempty"`
	Required bool               `json:"required,omitempty"`
	Style    string             `json:"style,omitempty"`
	Schema   Schema             `json:"schema,omitempty"`
	Examples map[string]Example `json:"examples,omitempty"`
}

type Schema struct {
	Type                 string            `json:"type,omitempty"`
	Properties           map[string]Schema `json:"properties,omitempty"`
	Description          string            `json:"description,omitempty"`
	Format               string            `json:"format,omitempty"`
	OneOf                []Schema          `json:"oneOf,omitempty"`
	Ref                  string            `json:"$ref,omitempty"`
	Required             []string          `json:"required,omitempty"`
	AdditionalProperties bool              `json:"additionalProperties,omitempty"`
	Encoding             map[string]any    `json:"encoding,omitempty"`
}

type RequestBody struct {
	Ref         string             `json:"$ref,omitempty"`
	Description string             `json:"description,omitempty"`
	Content     map[string]Content `json:"content,omitempty"`
	Required    bool               `json:"required,omitempty"`
}

type Content struct {
	Schema      Schema             `json:"schema,omitempty"`
	Examples    map[string]Example `json:"examples,omitempty"`
	Description string             `json:"description,omitempty"`
}

type Response struct {
	Description string             `json:"description,omitempty"`
	Content     map[string]Content `json:"content,omitempty"`
}

type Path map[string]any

type Method struct {
	Summary     string              `json:"summary,omitempty"`
	Parameters  []Parameter         `json:"parameters,omitempty"`
	RequestBody *RequestBody        `json:"requestBody,omitempty"`
	Responses   map[string]Response `json:"responses,omitempty"`
}

func (m *Method) WithParams(params []Parameter) *Method {
	if len(params) > 0 {
		m.Parameters = params
	}
	return m
}

type Components struct {
	RequestBodies map[string]RequestBody `json:"requestBodies,omitempty"`
	Schemas       map[string]Schema      `json:"schemas,omitempty"`
	Examples      map[string]Example     `json:"examples,omitempty"`
	Parameters    map[string]Parameter   `json:"parameters,omitempty"`
}
